In [1]:
import pandas as pd

# Loading dataset
data = pd.read_csv('StudentsPerformance.csv')

# Show first 5 rows
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
# Convert categorical columns into numbers
data = pd.get_dummies(data)

# Show updated data
data.head()

,math score,reading score,writing score,gender_female,gender_male,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_free/reduced,lunch_standard,test preparation course_completed,test preparation course_none
0,72,72,74,True,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,True
1,69,90,88,True,False,False,False,True,False,False,False,False,False,False,True,False,False,True,True,False
2,90,95,93,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,True
3,47,57,44,False,True,True,False,False,False,False,True,False,False,False,False,False,True,False,False,True
4,76,78,75,False,True,False,False,True,False,False,False,False,False,False,True,False,False,True,False,True

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Features (input)
X = data.drop('writing score', axis=1)

# Target (output)
y = data['writing score']

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained successfully!!!!")

Model trained successfully!

In [4]:
from sklearn.metrics import mean_absolute_error

# Make predictions on test data
y_pred = model.predict(X_test)

# Check error (accuracy measure)
error = mean_absolute_error(y_test, y_pred)

print("Mean Absolute Error:", error)

# Make a sample prediction
sample = X_test.iloc[0].values.reshape(1, -1)
prediction = model.predict(sample)

print("Actual Value:", y_test.iloc[0])
print("Predicted Value:", prediction[0])

Mean Absolute Error: 2.9594934664513226
Actual Value: 78
Predicted Value: 74.32729872222981

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(